In [2]:
import dataloader
import random
import numpy as np
import os
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torch.autograd import Variable
#from sklearn.model_selection import train_test_split
import torchvision
import torchvision.transforms as transforms
from PIL import Image
import cv2
import matplotlib.pyplot as plt
import glob
import matplotlib.pyplot as plt


In [3]:
from dataloader import Dataload

batch_size = 32

train_dataloader = Dataload(r"E:\Dataset\training_set\train",same_matrix=False)
train_loader= DataLoader(
    dataset = train_dataloader,
    batch_size = batch_size,
    shuffle = True,
    drop_last = True
)


E:\Dataset\training_set\train\images\ E:\Dataset\training_set\train\labels\
total: 537


In [6]:
train_loader.dataset

In [4]:
for data in train_loader:
    img,label = data
    print(label.shape)

RuntimeError: stack expects each tensor to be equal size, but got [1, 5] at entry 0 and [2, 5] at entry 1

In [3]:
len(train_loader)

537


16

In [5]:
a = torch.zeros((128,25,4))
b = torch.zeros((128,25,4))

In [6]:
d = torch.nn.MSELoss()
d(a.float(), b.float())

tensor(0.)

In [12]:
a = [[1,2,3],[3,4]]

In [13]:
len(a[0])

3

In [10]:
for data in train_loader:
    print(type(data))

RuntimeError: stack expects each tensor to be equal size, but got [3, 5] at entry 0 and [2, 5] at entry 1

In [6]:
b

tensor([[4.0000, 0.8214, 0.0566, 0.0545, 0.0612],
        [4.0000, 0.4405, 0.8041, 0.0444, 0.0791]])

##判断里面标签的个数

In [11]:
import os
import glob
file_path =r'E:\Dataset\training_set\train\labels'
file = glob.glob(file_path+'/*.txt')
# print(file)
maxNum = 0

for i in file:
    label = []
    with open(i) as f:
        lines = f.readlines()
        for line in lines:
            x = line.replace('\n', '').split(' ')
            x = [float(i) for i in x]
            label.append(x)
    if(len(label)>maxNum):
        maxNum = len(label)
        print(i)

print(maxNum)

E:\Dataset\training_set\train\labels\430.txt
E:\Dataset\training_set\train\labels\433.txt
E:\Dataset\training_set\train\labels\443.txt
E:\Dataset\training_set\train\labels\591.txt
E:\Dataset\training_set\train\labels\738.txt
20


In [34]:
b = np.tile(b,(50,1))
b.shape

(100, 5)

In [14]:
catr = torch.nn.Flatten(a)
catr1 = torch.nn.Flatten(b)

res = torch.cat((a,b))
res

RuntimeError: Tensors must have same number of dimensions: got 3 and 2

In [20]:
ones = -1 * np.ones(500).reshape([100,5])

In [37]:
b +ones

ValueError: operands could not be broadcast together with shapes (2,5) (100,5) 

In [25]:
ones

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -

In [46]:
l,m = b.shape
l,m

(2, 5)

In [43]:
ones[:2,:] = b

In [44]:
ones

array([[ 4.        ,  0.82139152,  0.056585  ,  0.0545007 ,  0.06118967],
       [ 4.        ,  0.44054589,  0.80414975,  0.0443917 ,  0.07911392],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1. 

In [30]:
d = a.numpy()
d[0,:,:].shape

(128, 128)

In [39]:
pt,label= train_dataloader[966-430]
print(pt,label)

list index out of range


UnboundLocalError: local variable 'image' referenced before assignment

In [40]:
for i in  range(0,966-430):

    pt,label= train_dataloader[i]
    print(i,pt,label)

[[0.0, 0.34756944444444443, 0.07827360733695651, 0.057367149758454083, 0.028659986413043473], [0.0, 0.24378019323671493, 0.4301545516304348, 0.046044685990338154, 0.0382133152173913], [0.0, 0.42456219806763285, 0.38981827445652173, 0.04830917874396137, 0.029721467391304324], [0.0, 0.34907910628019323, 0.5930918817934783, 0.03925120772946858, 0.049889605978260865], [0.0, 0.5336352657004831, 0.6971170176630435, 0.029438405797101396, 0.06899626358695654], [0.0, 0.9804951690821258, 0.7708899456521738, 0.024909420289855037, 0.06156589673913049]]
宽高为 2048 2880 
0 tensor([[[0.3920, 0.3920, 0.4237,  ..., 0.3602, 0.4079, 0.3920],
         [0.3920, 0.4396, 0.4237,  ..., 0.3920, 0.4079, 0.4079],
         [0.4396, 0.3920, 0.4396,  ..., 0.3920, 0.3761, 0.4079],
         ...,
         [0.4079, 0.3602, 0.3602,  ..., 0.3920, 0.3920, 0.3920],
         [0.3920, 0.3920, 0.3920,  ..., 0.4079, 0.3920, 0.3920],
         [0.3920, 0.3920, 0.3920,  ..., 0.3920, 0.3920, 0.4237]],

        [[0.4679, 0.4679, 0.46

In [3]:
file_path = r"E:\Dataset\training_set\train"
middle = file_path + "\\images\\"
label_path = file_path + "\\labels\\"

print(middle, label_path)

file_path_list = glob.glob(middle+"*.png")
label_path_list = glob.glob(label_path+"*.txt")

E:\Dataset\training_set\train\images\ E:\Dataset\training_set\train\labels\


In [7]:
label_path_list[0]


'E:\\Dataset\\training_set\\train\\labels\\430.txt'

In [16]:
with open(label_path_list[0]) as f:
    lines = f.readlines()
    for line in lines:
        x = line.replace('\n','').split(' ')
        print(x)

['0', '0.34756944444444443', '0.07827360733695651', '0.057367149758454083', '0.028659986413043473']
['0', '0.24378019323671493', '0.4301545516304348', '0.046044685990338154', '0.0382133152173913']
['0', '0.42456219806763285', '0.38981827445652173', '0.04830917874396137', '0.029721467391304324']
['0', '0.34907910628019323', '0.5930918817934783', '0.03925120772946858', '0.049889605978260865']
['0', '0.5336352657004831', '0.6971170176630435', '0.029438405797101396', '0.06899626358695654']
['0', '0.9804951690821258', '0.7708899456521738', '0.024909420289855037', '0.06156589673913049']
